name: Build and deploy GraphQL data server

on:
  push:
    branches:
      - main
      - test
  workflow_dispatch:

jobs:
  build:
    name: Build Kotlin app with GraalVM
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

#      - name: Read package version
#        id: get-version
#        run: |
#          echo "BUILD_VERSION=$(grep -oP "version\s*=\s*'[^']+'" build.gradle.kts | grep -oP "[^']*" | tr -d '\n' | tr -d ' ' | tr -d 'version=')" >> "$GITHUB_OUTPUT"

      - name: Setup GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: 24
          distribution: 'graalvm'
          github-token: ${{ github.ACTION_TOKEN }}

      - name: Fix wrapper permission
        run: |
          chmod +x ./gradlew

      - name: Build native image
        run: |
          ./gradlew nativeCompile

      - name: Get the filename
        run: |
          echo "FILENAME=$(ls ./build/native/nativeCompile | grep akfgfragments-data-grphql-server)" >> $GITHUB_ENV

      - name: Upload artifact
        uses: actions/upload-artifact@v5
        with:
          name: 'built-app'
          path: ${{ env.FILENAME }}
          if-no-files-found: error

  deploy:
    name: Deploy the built app to the server
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Define path
        id: define-path
        run: |
          if [ ${{ github.ref }} -eq 'refs/heads/main' ]; then
            echo "PATH=${{ secrets.DATA_SERVER_PATH }}" >> "$GITHUB_OUTPUT"
          else
            echo "PATH=${{ secrets.DATA_SERVER_PATH_TEST }}" >> "$GITHUB_OUTPUT"

      - name: Download artifact
        uses: actions/download-artifact@v6
        with:
          name: 'built-app'

      - name: Copy to the server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.IP }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          source: ${{ env.FILENAME }}
          target: ${{ steps.define-path.outputs.PATH }}

      - name: Change symlink and restart the app
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: |
            cd ${{ steps.define-path.outputs.path }}
            ln -sfn $FILENAME data-server
            systemctl restart data-server
          host: ${{ secrets.IP }}
          username: ${{ secrets.USER }}
          privateKey: ${{ secrets.SSH_KEY }}